### ISSUE TITLE
MTS Тарифище

### ISSUE THREAD

**Issue by Ku6epMeH** [cyborg-one/nfqttl-src#2]
iptables -t mangle -A PREROUTING -i eth_x -j TTL --ttl-inc 4
Edit:
iptables -t mangle -I PREROUTING -j TTL --ttl-inc 4

**Comment by cyborg-one** [comment]
Вам нужен механизм инкремент?
Почему именно 4?

**Comment by Makar0n-pro** [comment]
> Вам нужен механизм инкремент?
> Почему именно 4?
Fixing TTL on 64, in addition, in the second line, a way to bypass new tricks of MTS
```
iptables -t mangle -A POSTROUTING -j TTL --ttl-set 64

iptables -t mangle -I PREROUTING -j TTL --ttl-inc 1
```
Inversion of access point traffic in donor vpn
```
iptables -t filter -F FORWARD
iptables -t nat -F POSTROUTING
iptables -t filter -I FORWARD -j ACCEPT
iptables -t nat -I POSTROUTING -j MASQUERADE
ip rule add from 192.168.43.0/24 lookup 61
ip route add default dev tun0 scope link table 61
ip route add 192.168.43.0/24 dev ap0 scope link table 61
ip route add broadcast 255.255.255.255 dev ap0 scope link table 61
```
ap0 - network interface of the access point
tun0 - network interface of your VPN client
ppp0 - network interface built into your android VPN
